"""empty message

Revision ID: 2438c59395f7
Revises: 6bdea0d8a219
Create Date: 2022-03-06 01:18:16.402618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2438c59395f7'
down_revision = '6bdea0d8a219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('edited', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('person', 'updated')
    op.add_column('planet', sa.Column('edited', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('planet', 'updated')
    op.add_column('user', sa.Column('edited', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user', 'updated')
    op.add_column('vehicle', sa.Column('edited', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('vehicle', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'edited')
    op.add_column('user', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user', 'edited')
    op.add_column('planet', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('planet', 'edited')
    op.add_column('person', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('person', 'edited')
    # ### end Alembic commands ###
