"""empty message

Revision ID: 5ee6614c596a
Revises: 8400cfbbb6cd
Create Date: 2022-03-08 11:23:27.542396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee6614c596a'
down_revision = '8400cfbbb6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('films', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('pilots', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'pilots')
    op.drop_column('vehicle', 'films')
    # ### end Alembic commands ###
