"""empty message

Revision ID: 6bdea0d8a219
Revises: 7eeea15475b6
Create Date: 2022-03-06 01:17:06.769811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdea0d8a219'
down_revision = '7eeea15475b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('planet', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicle', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'updated')
    op.drop_column('user', 'updated')
    op.drop_column('planet', 'updated')
    op.drop_column('person', 'updated')
    # ### end Alembic commands ###
