"""empty message

Revision ID: 7eeea15475b6
Revises: bd01fb2e235f
Create Date: 2022-03-04 17:56:39.097450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eeea15475b6'
down_revision = 'bd01fb2e235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'nature')
    op.drop_column('planet', 'nature')
    op.drop_column('vehicle', 'nature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('nature', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('planet', sa.Column('nature', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('nature', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
