"""empty message

Revision ID: 8400cfbbb6cd
Revises: 2438c59395f7
Create Date: 2022-03-08 11:20:51.012994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8400cfbbb6cd'
down_revision = '2438c59395f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('passengers', sa.String(length=120), nullable=True))
    op.drop_column('vehicle', 'passagers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('passagers', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'passengers')
    # ### end Alembic commands ###
