"""empty message

Revision ID: bd01fb2e235f
Revises: adaeaa39705b
Create Date: 2022-03-03 19:04:19.125147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd01fb2e235f'
down_revision = 'adaeaa39705b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('nature', sa.String(length=120), nullable=False))
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('person', 'edited')
    op.add_column('planet', sa.Column('nature', sa.String(length=120), nullable=False))
    op.alter_column('planet', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('planet', 'edited')
    op.add_column('user', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicle', sa.Column('nature', sa.String(length=120), nullable=False))
    op.alter_column('vehicle', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('vehicle', 'edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('edited', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('vehicle', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('vehicle', 'nature')
    op.drop_column('user', 'created')
    op.add_column('planet', sa.Column('edited', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('planet', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('planet', 'nature')
    op.add_column('person', sa.Column('edited', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('person', 'nature')
    # ### end Alembic commands ###
